# Generated by Django 5.2.6 on 2025-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
